# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-23 22:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book_app', '0001_initial'),
        ('login_registration', '0002_auto_20170923_1509'),
        ('review_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='book',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='book_app.Book'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='review',
            name='user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='login_registration.User'),
            preserve_default=False,
        ),
    ]
